spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      server:
        native:
          search-locations:
            - classpath:config/telemetry/{application}

server:
  port: 8888
