FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Копируем jar из target текущего модуля
# Имя файла подстроится под artifactId и version из pom.xml этого модуля
COPY target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
