# Kafka bootstrap servers
kafka.bootstrap.servers=localhost:9092

# Kafka topics
kafka.topic.hub.events=telemetry.hubs.v1
kafka.topic.sensor.events=telemetry.sensors.v1

# Optional: additional Kafka producer settings
kafka.producer.acks=1
kafka.producer.retries=3
kafka.producer.batch.size=16384
